server:
  port: 8080

spring:
  application:
    name: student

  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/student
    password: 'postgres'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'